import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { IoIosSearch } from "react-icons/io";
import { IoBagOutline } from "react-icons/io5";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className='flex flex-col w-l h-20 items-center gap-6 pt-8 bg-black w-xl'>
        <h1 className='text-white text-2xl font-bold'><span className='text-amber-500'>Food</span>tuck</h1>
        <nav className='flex w-lx justify-between items-center'>
          <ul className='text-white flex gap-4 text-xl'>
            <li>Home</li>
            <li>Menu</li>
            <li>Blog</li>
            <li>Pages</li>
            <li>About</li>
            <li>Shop</li>
            <li>Contact</li>
          </ul>
          <div className='flex items-center'>
          <input type="text" placeholder='search...' className='border-2 rounded-3xl border-amber-500 bg-black w-80 h-12 pl-9' />
          <div className='relative right-10'><IoIosSearch size={24} color='white' /></div>
          <IoBagOutline size={24} color='white'/>
          </div>
        </nav>
      </div>
      <div className="">
        {children}
      </div>
        
      </body>
    </html>
  );
}
